### ISSUE TITLE
CI run of cython on windows fails

### ISSUE THREAD

**Issue by mattip** [pypy/binary-testing#13]
The [cython run on windows](https://github.com/pypy/binary-testing/runs/5063220731?check_suite_focus=true) is failing with
```
c1: fatal error C1081: 
'D:\a\binary-testing\binary-testing\cython\TEST_TMP\2\pyximport\pyximport_pyimport_only\TEST_TMP\temp.win-amd64-3.8\Release\a\binary-testing\binary-testing\cython\TEST_TMP\2\pyximport\pyximport_pyimport_only\TEST_TMP\temp.win-amd64-3.8\Release\a\_temp\46f8a4af-7ee0-4d9a-a854-a794a2900cc7\pypy-c-jit-104827-0360402c9455-win64\Lib\encodings\mbcs.obj': 
file name too long
```

The CI is running `python runtests.py -vv --no-code-style -x Debugger --backends=c -j7`. Is there something the [cython appveyor run](https://github.com/cython/cython/blob/21059e9b69105c239ca488d93d709ef634af23fe/appveyor.yml#L125) is doing that [this repo](https://github.com/pypy/binary-testing/blob/008bbe5e4d3c597b891232fe32c61b8d3d211bc8/.github/workflows/cython.yml#L80) is not doing?

**Comment by mattip** [comment]
The limit is 260, that name is 267.

**Comment by mattip** [comment]
Windows need cython/cython#4630, which is stuck waiting for cython/cython#4625

**Comment by scoder** [comment]
Fixed by https://github.com/cython/cython/pull/4630

**Comment by mattip** [comment]
Cool. Now a windows pypy nightly [run](https://github.com/pypy/binary-testing/runs/7383181232?check_suite_focus=true) has "only" about 70 failing tests, where linux passes.

17 of them are [of the form](https://github.com/pypy/binary-testing/runs/7383181232?check_suite_focus=true#step:7:34902)
```
ERROR: test_pure (Cython.Build.Tests.TestInline.TestInline)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\binary-testing\binary-testing\cy\Cython\Build\Tests\TestInline.py", line 68, in test_pure
    """, a=3, **self.test_kwds)
  File "D:\a\binary-testing\binary-testing\cy\Cython\Shadow.py", line 135, in inline
    return _cython_inline(f, *args, **kwds)
  File "D:\a\binary-testing\binary-testing\cy\Cython\Build\Inline.py", line 283, in cython_inline
    module = load_dynamic(module_name, module_path)
  File "D:\a\binary-testing\binary-testing\cy\Cython\Build\Inline.py", line 47, in load_dynamic
    module = _importlib_util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<builtin>/frozen importlib._bootstrap_external", line 1180, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: The parameter is incorrect
```

I don't see those in the [complementary run](https://github.com/cython/cython/runs/7273324497?check_suite_focus=true) of PR cython/cython#4324 so it seems like a PyPy-specific issue in `_call_with_frames_removed`

**Comment by mattip** [comment]
Down to one failing test on windows (which now started appearing on ubuntu as well:
```
Errors from shard 0:
======================================================================
FAIL: coerce_to_charptr (bytearray_coercion)
Doctest: bytearray_coercion.coerce_to_charptr
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/_temp/7ed94a14-4d41-419e-9be9-c83147194cb9/pypy-c-jit-107909-28d9e130d140-linux64/lib/pypy3.10/doctest.py", line 2223, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for bytearray_coercion.coerce_to_charptr
  File "/home/runner/work/binary-testing/binary-testing/cy/TEST_TMP/0/run/c/bytearray_coercion/bytearray_coercion.pypy310-pp73-x86_64-linux-gnu.so", line unknown line number, in coerce_to_charptr

----------------------------------------------------------------------
File "/home/runner/work/binary-testing/binary-testing/cy/TEST_TMP/0/run/c/bytearray_coercion/bytearray_coercion.pypy310-pp73-x86_64-linux-gnu.so", line ?, in bytearray_coercion.coerce_to_charptr
Failed example:
    coerced == b or (coerced, b)
Expected:
    True
Got:
    (bytearray(b'abc\xc41\x7f'), bytearray(b'abc'))
```

**Comment by mattip** [comment]
As noted in cython/cython#5833, `PyByteArray_AsString` is not adding a `\0` to the returned string, even though [it should](https://docs.python.org/3/c-api/bytearray.html#c.PyByteArray_AsString).

**Comment by mattip** [comment]
The bytearray code was changed to add a `\0`, and windows runs are passing. There is a spurious macOS failure around time in c vs time in python, but that is a different issue. Closing.
