### ISSUE TITLE
CI run of cython on macOS is failing

### ISSUE THREAD

**Issue by mattip** [pypy/binary-testing#22]
This passes
```
pypy3.8 runtests.py -vv py_unicode_strings 
pypy3.8 runtests.py -vv charptr_from_temp

```
This fails ~50% of the runs
```
pypy3.8 runtests.py -vv py_unicode_strings charptr_from_temp
```

with this output
```
Python 3.8.13 (4b1398fe9d76ad762155d03684c2a153d230b2ef, Mar 29 2022, 08:30:05)
[PyPy 7.3.9 with GCC Apple LLVM 13.0.0 (clang-1300.0.29.30)]

Running tests against Cython 3.0.0a10 b6ca1a2e20a4f6e38bf8d9796e91ff3ab22b8971
Disabling refnanny in PyPy
Using Cython language level 2.
Test dependency not found: 'numpy'
Test dependency not found: 'pythran'
Test dependency found: 'setuptools.sandbox' version 59.8.0
Test dependency found: 'asyncio' version 3.8.13
Test dependency found: 'pstats' version 3.8.13
Test dependency found: 'posix' version 3.8.13
Test dependency found: 'array' version 3.8.13
Test dependency not found: 'Cython.Coverage'
Test dependency not found: 'Cython.Coverage'
Test dependency not found: 'IPython.testing.globalipapp'
Test dependency not found: 'jedi_BROKEN_AND_DISABLED'
Test dependency found: 'test.support' version 3.8.13
Backends: c

runTest (__main__.CythonCompileTestCase)
[-1] compiling (c/cy2) charptr_from_temp ... ok
runTest (__main__.CythonRunTestCase)
[-1] compiling (c/cy2) and running charptr_from_temp ... test_charptr_and_charptr_func (charptr_from_temp)
Doctest: charptr_from_temp.test_charptr_and_charptr_func ... ok
test_charptr_and_ucharptr (charptr_from_temp)
Doctest: charptr_from_temp.test_charptr_and_ucharptr ... ok
test_more_args_adding (charptr_from_temp)
Doctest: charptr_from_temp.test_more_args_adding ... ok
test_more_args_indexing (charptr_from_temp)
Doctest: charptr_from_temp.test_more_args_indexing ... ok
test_more_args_slicing (charptr_from_temp)
Doctest: charptr_from_temp.test_more_args_slicing ... ok
test_one_arg_adding (charptr_from_temp)
Doctest: charptr_from_temp.test_one_arg_adding ... ok
test_one_arg_indexing (charptr_from_temp)
Doctest: charptr_from_temp.test_one_arg_indexing ... ok
test_one_arg_slicing (charptr_from_temp)
Doctest: charptr_from_temp.test_one_arg_slicing ... ok
runTest (__main__.CythonRunTestCase)
[-1] compiling (c/cy2) and running py_unicode_strings ... test_c_to_python (py_unicode_strings)
Doctest: py_unicode_strings.test_c_to_python ... ok
test_python_to_c (py_unicode_strings)
Doctest: py_unicode_strings.test_python_to_c ... FAIL

======================================================================
FAIL: test_python_to_c (py_unicode_strings)
Doctest: py_unicode_strings.test_python_to_c
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/matti/oss/pypy3.8-v7.3.9-osx64/lib/pypy3.8/doctest.py", line 2206, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for py_unicode_strings.test_python_to_c
  File "/Users/matti/oss/cython/TEST_TMP/run/c/py_unicode_strings/py_unicode_strings.pypy38-pp73-darwin.so", line unknown line number, in test_python_to_c

----------------------------------------------------------------------
File "/Users/matti/oss/cython/TEST_TMP/run/c/py_unicode_strings/py_unicode_strings.pypy38-pp73-darwin.so", line ?, in py_unicode_strings.test_python_to_c
Failed example:
    test_python_to_c()
Exception raised:
    Traceback (most recent call last):
      File "/Users/matti/oss/pypy3.8-v7.3.9-osx64/lib/pypy3.8/doctest.py", line 1339, in __run
        compileflags, 1), test.globs)
      File "<doctest py_unicode_strings.test_python_to_c[0]>", line 1, in <module>
        test_python_to_c()
      File "tests/run/py_unicode_strings.pyx", line 98, in py_unicode_strings.test_python_to_c (py_unicode_strings.c:3450)
        assert_Py_UNICODE_equal(uwide_literal, <Py_UNICODE*>c_pu_wide_literal)
      File "tests/run/py_unicode_strings.pyx", line 12, in py_unicode_strings.assert_Py_UNICODE_equal (py_unicode_strings.c:2216)
        assert u1[i] == u2[i], f"Mismatch at position {i}: {<long>u1[i]} != {<long>u2[i]} ({u1!r} != {u2!r})"
    AssertionError: Mismatch at position 2: 786432 != 0 ('��\U000c0000' != '��')


----------------------------------------------------------------------
Ran 13 tests in 3.424s

FAILED (failures=1)
Most expensive pipeline stages: 'AnalyseDeclarationsTransform': 0.23 / 5 (0.046 / run), 'generate_pyx_code_stage': 0.17 / 2 (0.085 / run), 'DecoratorTransform': 0.07 / 5 (0.014 / run), 'parse': 0.07 / 5 (0.013 / run), 'RemoveUnreachableCode': 0.06 / 10 (0.006 / run), 'IterationTransform': 0.06 / 5 (0.011 / run), 'MarkClosureVisitor': 0.05 / 5 (0.011 / run), 'AnalyseExpressionsTransform': 0.05 / 5 (0.010 / run), 'SwitchTransform': 0.05 / 5 (0.010 / run), 'PostParse': 0.05 / 5 (0.009 / run)
Times:
cython      :     2.09 sec  (   3,  0.696 / run) - slowest: 'c:py_unicode_strings' (0.85s), 'c:charptr_from_temp' (0.64s), 'c:charptr_from_temp' (0.59s)
compile-c   :     0.91 sec  (   2,  0.456 / run) - slowest: 'c:charptr_from_temp' (0.50s), 'c:py_unicode_strings' (0.41s)
import      :     0.23 sec  (   2,  0.113 / run) - slowest: 'c:py_unicode_strings' (0.12s), 'c:charptr_from_temp' (0.11s)
run         :     0.03 sec  (   2,  0.015 / run) - slowest: 'c:charptr_from_temp' (0.02s), 'c:py_unicode_strings' (0.01s)
ALL DONE

```

**Comment by mattip** [comment]
It fails the same with `--jit off`

**Comment by mattip** [comment]
Not sure, but this seems to have dissappeared. Closing.
